spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_learning?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis-plus:
  mapper-locations:
    - classpath*:com/codeman/**/xml/*Mapper.xml
    - classpath:mapper/*.xml
    - classpath:dao/*.xml


jwt:
  tokenHeader: token #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头