spring:
  datasource:
    url: jdbc:mysql://localhost:3306/universe?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis-plus:
  mapper-locations:
    - classpath*:com/codeman/**/xml/*Mapper.xml
    - classpath:mapper/*.xml
    - classpath:dao/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
