server:
  port: 8066
#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: kafka-group
#      # 手动提交: 设置非自动提交
#      enable-auto-commit: false
#    listener:
#      # 手动提交: 设置手动提交模式
#      ack-mode: manual