server:
  port: 8080
  tomcat: # 必须添加tomcat格式
    uri-encoding: UTF-8
spring:
  application:
    name: dubbo-producer
  main:
    allow-bean-definition-overriding: true
  # Nacos配置
  cloud:
    nacos:
      discovery: # 服务注册中心地址
        server-addr: 106.14.219.67:8848

dubbo:
  application:
    version: 1.0.0
    logger: slf4j
  # 扫描路径
  scan:
    base-packages: com.codeman.dubbo
  registry:
    address: spring-cloud://106.14.219.67
  # [ˈprəʊtəkɒl]协议
  protocol:
    name: dubbo
    port: 28080 # 该端口与dubbo-producer不一致
    threads: 200
    accesslog: D:/logs/hdgaadd/dubbo-producer.log